name: custom_chat_gpt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  sliding_up_panel: ^2.0.0+1
  scale_button: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/icons/
